export const product = [
{
    id: 1,
    img:"https://www.cookwithmanali.com/wp-content/uploads/2013/09/Paneer-Paratha-Homemade.jpg",
    name:"Mom's style Ajwaini Parantha",
    desc:"Ajwain has such a tantalising aroma and that it can pep up adish as a standarlone spice.You will rea...",
    price: 1,
    prevPrice:50,
},
{
    id: 2,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 3,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 4,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 5,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 6,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 7,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 8,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 9,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 10,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 11,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
},
{
    id: 12,
    img:"https://champagne-tastes.com/wp-content/uploads/2016/08/toasted-muesli-small-2-683x1024.webp",
    name:"Roasted cereal - Wheat jowar bajra",
    desc:"Roasted cereal - Wheat jowar bajra",
    price: 1,
    prevPrice:21,
}
];